### ISSUE TITLE
Part of the text set to the content of Atom::Entry is not escaped

### ISSUE THREAD

**Issue by rnanba** [lyokato/ruby-atomutil#2]
I'm using atomutil 0.1.4 with ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]. The following code outputs `&lt;` and `&gt;` to `content` element content without being escaped.

```
# coding: utf-8
require 'atomutil'
entry = Atom::Entry.new
entry.content = "&lt;br&gt;"
puts entry.to_s
```

result:
```
<?xml version='1.0' encoding='UTF-8'?><entry xmlns='http://www.w3.org/2005/Atom'><content type='text'>&lt;br&gt;</content></entry>
```

expected:
```
<?xml version='1.0' encoding='UTF-8'?><entry xmlns='http://www.w3.org/2005/Atom'><content type='text'>&amp;lt;br&amp;gt;</content></entry>
```

The example above is assumed to be "In the blog service accepting posts in text format that can write HTML tags (such as Hatena Blog in Hatena-Notation mode), describe tags with escaped form to explain HTML tags".

The expected result is that the source code of the `br` tag is displayed in the blog entry, but in fact the line feed is displayed (it functions as a real `br` tag).

The cause of this issue is that `value.elem.text` in https://github.com/lyokato/ruby-atomutil/blob/954c5d1b387bff63db3462d19d3f7abf196d2b1f/lib/atomutil.rb#L526 returns double unescaped string. This is the bug of `REXML::Text#value` I think, but the maintainer of REXML answered that it can not be fixed because compatibility breaks (see https://bugs.ruby-lang.org/issues/15057).

Instead, following patch was proposed. Would you please apply it?

```
diff --git a/lib/atomutil.rb b/lib/atomutil.rb
index 9bb9e0c..6d9b985 100644
--- a/lib/atomutil.rb
+++ b/lib/atomutil.rb
@@ -523,7 +523,10 @@ module Atom
             element.add_attribute a
           end
         end
-        element.text = value.elem.text unless value.elem.text.nil?
+        text = value.elem.get_text
+        unless text.nil?
+          element.text = REXML::Text.new(text.to_s, true, nil, true)
+        end
       else
         if value.is_a?(REXML::Element)
           element.add_element value.deep_clone
```

**Comment by lyokato** [comment]
applied.

https://github.com/lyokato/ruby-atomutil/pull/5/files

thanks!
